color: null
fieldLayouts:
  314938cb-6964-44c0-b091-e3b5e6f9092d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c816fa6-4849-42ca-ad90-6b8a02dbb6bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9cb6112-ebae-420b-bae9-a54c387419f6 # Footer Nav
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a321ae4c-b892-4ecf-b2d4-a1b215a03745
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e84a81b-e9de-452f-9a8e-77339233eb86
        userCondition: null
handle: acclaroDrums
hasTitleField: true
icon: ''
name: 'acclaro drums'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: ''
titleTranslationMethod: language
