fieldLayouts:
  9c553322-4fb1-424e-a70a-dae752c4dd71:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f16f2cc-e44e-4637-8ab8-820046e6fcf1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5aeca72-2e2c-4f00-a552-a6553a24dce1 # Navigation Field
            instructions: 'Please Read me.'
            label: 'Convert me'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 800ddac4-71a9-4240-a77f-f203b3befd3f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 111ed88d-a0cd-4ac9-85fc-d3f1a51568af
        userCondition: null
handle: aNavSection
hasTitleField: false
name: 'A Nav Section'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
