fieldLayouts:
  d6f540a3-cd8e-40e2-aaed-61f9aed92b1e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1f3b342e-a968-45c8-81e0-c2e38edd7916
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 891c8373-a143-43b3-a0a1-8b437e97304e # A nested Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ecb718c-ed22-4116-9685-e1431292e09d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30cd9d5c-f866-4835-9564-fcc0b3509ad3
        userCondition: null
handle: aNestedEntryHandle
hasTitleField: true
name: 'A nested entry'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
