color: null
fieldLayouts:
  451b0588-1b1b-43a5-9c6b-dbb876a06ecd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ba6a126f-e44f-46c4-bd59-74ae6eec164f
            handle: null
            includeInCards: false
            instructions: null
            label: 'Navigation 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 320f1b2e-6fb7-4b2c-968f-37759d943c5b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3182e52f-cecb-4d68-a6e1-4d4bf560a926
        userCondition: null
handle: aSuperTableFiledsBlock
hasTitleField: false
icon: null
name: 'A Super table fileds Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
