color: null
fieldLayouts:
  ff64b600-8ab7-4dc4-a378-16752a6ee4e4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 21363914-6214-47a5-aa16-70c6d2bb79f8
            handle: null
            includeInCards: false
            instructions: null
            label: 'Child Fields'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: beb7cbcf-e2fe-4507-8986-c3b3c6c7a22c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f65eef9-66ee-4495-831f-e717cb354526
            handle: null
            includeInCards: true
            instructions: null
            label: 'Child Fields 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0972bd2d-08d5-4ef1-8c38-3b59c155f634
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 070a71ee-7433-4283-9570-ed810fb44670
        userCondition: null
handle: childBlock
hasTitleField: false
icon: null
name: 'Child block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
