fieldLayouts:
  ddaee9e2-36b6-43c1-acdc-2791aac393fd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 41757327-2432-49b8-a527-467175f9177c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d3fad61c-dfb9-4da2-bb75-6d2910c3c4ca # Plain Text 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44383177-a17e-4a93-905f-3dfed4683f7d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43e392f6-b59f-4660-b9b8-27dea006efc3
        userCondition: null
handle: default
hasTitleField: true
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
