fieldLayouts:
  ca3cb464-d4fa-4a4f-9e32-fbae5d9934ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 59ac8060-5855-4e95-bd50-36507c579de8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e5432bd-eb9b-481a-baa1-77cfbecbd529 # My ck title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2829854-cc6a-4ffd-a54c-f6bd17cca7df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00aaa976-8d91-470d-bb65-e8e15c8b2835
        userCondition: null
handle: heroCkEditor
hasTitleField: false
name: 'Hero ck editor'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
