fieldLayouts:
  1b9f4c8e-9d9f-4e83-8fe9-22f5b5892a45:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 22803a4d-1cbf-43ab-8819-549c8df61e86 # Hypers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31dbf026-a6a1-42b2-b04e-f25c8d907f49
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9575275a-07f4-4c11-840d-ebef47691b5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 635e5891-d26d-4beb-a140-afaa7e914729
        userCondition: null
handle: Hypers
hasTitleField: true
name: 'Hypers add'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
