fieldLayouts:
  68b5c339-7339-453b-9f10-0804748b0fc7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f8751def-5e0a-4e40-b4f9-eeb99dd7101a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab483db7-5488-4392-b2d6-4a5bc885bd11
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22803a4d-1cbf-43ab-8819-549c8df61e86 # Hypers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5c1f0ce-a26f-4ffc-88bd-d8c2bdb918be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5c63a1f1-d0ca-4b20-b771-b65cb882991b
        userCondition: null
handle: intro
hasTitleField: true
name: Introduction
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
