defaultPlacement: end
fieldLayouts:
  2e756f2d-e91f-4982-a4f0-225484d01f7a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 34075f1a-6b34-41f9-801e-e4ca10225f83
            warning: null
            width: 100
        name: Content
        uid: 11c8680f-1688-4014-b510-a178591d1263
handle: equipmentTypes
name: 'Equipment Types'
siteSettings:
  31c98fcc-97ce-40f9-bc6e-ff05853624ff: # Dutch
    hasUrls: true
    template: _views/categories/equipment
    uriFormat: 'equipment/{slug}'
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    hasUrls: true
    template: _views/categories/equipment
    uriFormat: 'equipment/{slug}'
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    hasUrls: true
    template: _views/categories/equipment
    uriFormat: 'equipment/{slug}'
  e57db4c9-d175-4d90-a17b-56a4a2b6fd61: # French
    hasUrls: true
    template: _views/categories/equipment
    uriFormat: 'equipment/{slug}'
structure:
  maxLevels: 1
  uid: d5ebc01f-7cb9-4f11-88d4-d42c8296248c
