columnSuffix: null
contentColumnType: text
handle: body
instructions: null
name: Body
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 81039de6-8440-4a7f-85f4-2e5753d11e15 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
