defaultPlacement: end
enableVersioning: true
entryTypes:
  - 473de3f9-0bc6-48fb-8a18-4b8a81438f3e # acclaro drums
handle: acclaroDrums
name: 'acclaro drums'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: acclaro-drums/_entry
    uriFormat: acclaro-drums
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
