defaultPlacement: end
enableVersioning: true
entryTypes:
  - 434e369c-884b-4e34-8dcb-63946f3bf52e # A new entry type
handle: aCraft5Sect
maxAuthors: 1
name: 'A craft5 sect'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  31c98fcc-97ce-40f9-bc6e-ff05853624ff: # Dutch
    enabledByDefault: true
    hasUrls: true
    template: a-craft5-sect/_entry
    uriFormat: 'a-craft5-sect/{slug}'
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: a-craft5-sect/_entry
    uriFormat: 'a-craft5-sect/{slug}'
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    enabledByDefault: true
    hasUrls: true
    template: a-craft5-sect/_entry
    uriFormat: 'a-craft5-sect/{slug}'
  e57db4c9-d175-4d90-a17b-56a4a2b6fd61: # French
    enabledByDefault: true
    hasUrls: true
    template: a-craft5-sect/_entry
    uriFormat: 'a-craft5-sect/{slug}'
type: channel
