defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7b8c33d5-84b4-4fc2-90e4-5f40d1b1454f # Top nav
handle: aFaNav
maxAuthors: 1
name: 'A fa nav'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: a-fa-nav/_entry
    uriFormat: 'a-fa-nav/{slug}'
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    enabledByDefault: true
    hasUrls: true
    template: a-fa-nav/_entry
    uriFormat: 'a-fa-nav/{slug}'
  e57db4c9-d175-4d90-a17b-56a4a2b6fd61: # French
    enabledByDefault: true
    hasUrls: true
    template: a-fa-nav/_entry
    uriFormat: 'a-fa-nav/{slug}'
type: channel
