defaultPlacement: end
enableVersioning: true
entryTypes:
  - 863e8c8e-f742-40c9-8840-ab92612b7ed5 # EntLinkit
handle: aLinkitOn
name: 'A linkit on'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: 'hyper/{slug}'
    uriFormat: 'hyper/{slug}'
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    enabledByDefault: true
    hasUrls: true
    template: 'hyper/{slug}'
    uriFormat: 'hyper/{slug}'
  e57db4c9-d175-4d90-a17b-56a4a2b6fd61: # French
    enabledByDefault: true
    hasUrls: true
    template: 'hyper/{slug}'
    uriFormat: 'hyper/{slug}'
type: channel
