defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7f6d1fe4-217c-4fbc-9812-1a7e5b1189c9 # A Nav Section
handle: aNavSection
name: 'A Nav Section'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: a-nav-section/_entry
    uriFormat: a-nav-section
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    enabledByDefault: true
    hasUrls: true
    template: a-nav-section/_entry
    uriFormat: a-nav-section
  e57db4c9-d175-4d90-a17b-56a4a2b6fd61: # French
    enabledByDefault: true
    hasUrls: true
    template: a-nav-section/_entry
    uriFormat: a-nav-section
type: single
