defaultPlacement: end
enableVersioning: true
entryTypes:
  - 859f9e22-62b1-44d2-b7f0-00911d874063 # New entry type 01
handle: aTestSection011
maxAuthors: 1
name: 'A test section 011'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  31c98fcc-97ce-40f9-bc6e-ff05853624ff: # Dutch
    enabledByDefault: true
    hasUrls: true
    template: a-test-section-011/_entry
    uriFormat: 'a-test-section-011/{slug}'
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: a-test-section-011/_entry
    uriFormat: 'a-test-section-011/{slug}'
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    enabledByDefault: true
    hasUrls: true
    template: a-test-section-011/_entry
    uriFormat: 'a-test-section-011/{slug}'
  e57db4c9-d175-4d90-a17b-56a4a2b6fd61: # French
    enabledByDefault: true
    hasUrls: true
    template: a-test-section-011/_entry
    uriFormat: 'a-test-section-011/{slug}'
type: channel
