defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0b6f81b0-efbb-446d-bc40-e3f2bdaf7f88 # A zero mat 01
handle: aZeroMat01
maxAuthors: 1
name: 'A zero mat 01'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  31c98fcc-97ce-40f9-bc6e-ff05853624ff: # Dutch
    enabledByDefault: true
    hasUrls: true
    template: a-zero-mat-01/_entry
    uriFormat: 'a-zero-mat-01/{slug}'
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: a-zero-mat-01/_entry
    uriFormat: 'a-zero-mat-01/{slug}'
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    enabledByDefault: true
    hasUrls: true
    template: a-zero-mat-01/_entry
    uriFormat: 'a-zero-mat-01/{slug}'
  e57db4c9-d175-4d90-a17b-56a4a2b6fd61: # French
    enabledByDefault: true
    hasUrls: true
    template: a-zero-mat-01/_entry
    uriFormat: 'a-zero-mat-01/{slug}'
structure:
  maxLevels: null
  uid: 031166a1-5fb4-469b-8403-3758dc36743b
type: structure
