defaultPlacement: end
enableVersioning: true
entryTypes:
  - 74313ad6-db0c-4c64-a2ae-ea69e418c6bf # Try new
handle: tryNew
name: 'Try new'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}/try-new'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _includes\components\heroTemplate\my-entry.twig
    uriFormat: try-new
  74347624-30b3-4f4d-a46d-7010dfdb3566: # Spanish-US
    enabledByDefault: true
    hasUrls: true
    template: _includes\components\heroTemplate\my-entry.twig
    uriFormat: try-new
  e57db4c9-d175-4d90-a17b-56a4a2b6fd61: # French
    enabledByDefault: true
    hasUrls: true
    template: _includes\components\heroTemplate\my-entry.twig
    uriFormat: try-new
type: single
